module.exports = {
    token: "",
    role: { joueurs: "", booster: "", contributeur: "" },
    roleStaff: "",
    cmd: { teamcreate: "" },

    team: {
        Tennis: "",
        Golfeur: "",
        Bloods: "",
        Ticon: "",
        Crips: "",
        LSSD: "",
        Sherif: "",
        Mecano: "",
        Militaire: "",
        Yakuza: "",
        Madrazo: "",
        FIB: "",
        Douanier: "",
        Clown: "",
        Eboueur: "",
        Prisonnier: "",
        Bennys: "",
        Fermier: "",
        Explorateur: "",
        Manuel: "",
        Geek: "",
        Cycliste: "",
        GIGN: "",
        Evade: "",
        LSPD: "",
        Dealer: "",
        Statue: "",
        EMS: "",
        Pilote: "",
        Armurier: "",
        Apu: "",
        Animateur: "",
        Lost: "",
        Ballas: "",
        Families: "",
        Business: "",
        Vagos: "",
        Instructeur: "",
        Pyjama: "",
        Professeur: "",
        Stagiaire: "",
        Ancien: "",
        Braqueur: "",
        Marabunta: "",
        Depanneur: "",
        Danseur: "",
        Zombie: "",
        Mexicain: "",
        Danois: "",
        Ingenieur: ""
    }
}